name: "Package Java Agnostic Serverless Functions"
description: "Package an Agnostic Serverless Function in Java to deploy it on a specific FaaS provider"
branding:
  icon: package
  color: red
inputs:
  faas-provider:
    description: "The provider to package the function for. Possible values are: azure, gcloud."
    required: true
  function-name:
    description: "The name of the function to be packaged"
    required: true
  working-directory:
    description: "The root directory of the function"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Package for Google Cloud Functions
      working-directory: ${{ inputs.working-directory }}
      run: "${GITHUB_ACTION_PATH}/package-${FAAS_PROVIDER}.sh"
      shell: bash
      env:
        APP_NAME: ${{ inputs.function-name }}
        DEPLOYMENT_DIR: deployment
        FAAS_PROVIDER: ${{ inputs.faas-provider }}
